#!/bin/bash

echo "🚀 Vercel Environment Setup Guide"
echo "================================"
echo ""
echo "This script will guide you through setting up Vercel for multiple environments."
echo ""
echo "📋 Prerequisites:"
echo "1. Vercel account created at https://vercel.com"
echo "2. GitHub repository connected to Vercel"
echo ""
echo "🔐 Step 1: Login to Vercel"
echo "Run: vercel login"
echo ""
echo "🔗 Step 2: Link your project"
echo "Run: vercel link"
echo ""
echo "📝 Step 3: Set up environment variables"
echo ""
echo "You can either:"
echo "A) Use Vercel Dashboard (recommended for first setup)"
echo "   - Go to https://vercel.com/dashboard"
echo "   - Select your project"
echo "   - Go to Settings → Environment Variables"
echo "   - Add variables for each environment"
echo ""
echo "B) Use CLI (after initial setup)"
echo "   Run: ./scripts/env-manager.sh push production"
echo "   Run: ./scripts/env-manager.sh push staging"
echo "   Run: ./scripts/env-manager.sh push development"
echo ""
echo "📊 Required Environment Variables:"
echo ""
echo "For ALL environments:"
echo "- BLIPEE_NEXT_PUBLIC_SUPABASE_URL"
echo "- BLIPEE_NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "- BLIPEE_SUPABASE_SERVICE_ROLE_KEY"
echo "- BLIPEE_SUPABASE_JWT_SECRET"
echo "- BLIPEE_POSTGRES_URL"
echo ""
echo "Environment-specific:"
echo "- NEXT_PUBLIC_APP_URL (different for each environment)"
echo "- NEXT_PUBLIC_ENVIRONMENT (development/staging/production)"
echo "- NODE_ENV (development/staging/production)"
echo ""
echo "🌍 Step 4: Configure domains"
echo "Production: retail-platform.vercel.app"
echo "Staging: retail-platform-staging.vercel.app"
echo "Development: retail-platform-development.vercel.app"
echo ""
echo "🚀 Step 5: Deploy"
echo "Run: ./scripts/deploy-env.sh production"
echo "Run: ./scripts/deploy-env.sh staging"
echo "Run: ./scripts/deploy-env.sh development"
echo ""
echo "✅ Setup complete!"