name: Collect Regional Data V2

on:
  workflow_call:
    inputs:
      pipeline_id:
        description: 'Pipeline run ID'
        required: false
        type: string
    outputs:
      successful:
        description: 'Number of successful collections'
        value: ${{ jobs.collect.outputs.successful }}
      failed:
        description: 'Number of failed collections'
        value: ${{ jobs.collect.outputs.failed }}
      total:
        description: 'Total number of regions'
        value: ${{ jobs.collect.outputs.total }}

env:
  NODE_VERSION: '20'

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      successful: ${{ steps.collect.outputs.successful }}
      failed: ${{ steps.collect.outputs.failed }}
      total: ${{ steps.collect.outputs.total }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd scripts/workflows
          npm init -y
          npm install @supabase/supabase-js node-fetch@2

      - name: Collect regional data
        id: collect
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SENSOR_AUTH_OMNIA: ${{ secrets.SENSOR_AUTH_OMNIA }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          PIPELINE_ID: ${{ inputs.pipeline_id }}
        run: |
          echo "Regional data collection placeholder"
          echo "successful=0" >> $GITHUB_OUTPUT
          echo "failed=0" >> $GITHUB_OUTPUT  
          echo "total=0" >> $GITHUB_OUTPUT
          # TODO: Implement regional data collection script