name: Run Analytics Aggregation

on:
  schedule:
    # Run every hour at 5 minutes past the hour
    - cron: '5 * * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  aggregate-analytics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm install node-fetch@2
      
      - name: Run analytics aggregation
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node scripts/run_hourly_aggregation.js
      
      - name: Send notification on failure
        if: failure()
        run: |
          echo "⚠️ Analytics aggregation failed. Check the logs for details."